Update sonarqube-generator.yml

diff --git a/.github/workflows/sonarqube-generator.yml b/.github/workflows/sonarqube-generator.yml
--- a/.github/workflows/sonarqube-generator.yml
+++ b/.github/workflows/sonarqube-generator.yml
@@ -37,17 +37,21 @@ jobs:
   
       - name: Build and scan
         # Wait for SonarQube to be ready before scanning
+        # Set timeout to 5 minutes (300 seconds)
         env:
           SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
           SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
         run: |
           cd jio
-          docker run -d --name sonarqube -e SONAR_ES_BOOTSTRAP_CHECKS_DISABLE=true -p 9000:9000 sonarqube:latest
           echo "Waiting for SonarQube to start..."
-          until $(curl --output /dev/null --silent --head --fail http://localhost:9000/api/system/health); do
+          SECONDS=0
+          TIMEOUT=300 
+          while ! curl --output /dev/null --silent --head --fail http://localhost:9000/api/system/health; do
               printf '.'
               sleep 5
-          done
-          echo "SonarQube is up and running!"
+              if [ $SECONDS -ge $TIMEOUT ]; then
+                  echo "SonarQube failed to start within $TIMEOUT seconds."
+                  exit 1
+              fi
           mvn -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.projectKey=OpenJio -Dsonar.projectName='OpenJio'
 
